version: "3.9"

services:
  webserver:
    image: nginx:1.21.3-alpine
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

  app:
    image: php:8.0-fpm-alpine
    volumes:
      - type: bind
        source: ./public/
        target: /var/www/public
        read_only: true